# Generated by Django 4.0.2 on 2022-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_color_alter_note_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
